import axiosWithAuth from "../../util/axiosWithAuth";

//mood action types

export const GET_FEATURED_PLAYLIST_START = "GET_FEATURED_PLAYLIST_START";
export const GET_FEATURED_PLAYLIST_SUCCESS = "GET_FEATURED_PLAYLIST_SUCCESS";
export const GET_FEATURED_PLAYLIST_FAIL = "GET_FEATURED_PLAYLIST_FAIL";
export const GET_FEATURED_PLAYLIST_RESOLVE = "GET_FEATURED_PLAYLIST_RESOLVE";
